---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ecom-service-pdb
  namespace: ecom
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ecom-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-service-pdb
  namespace: inventory
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: inventory-service
